In [26]:
import pandas as pd
import numpy as np

operacao = pd.read_csv("dados/operacao_2025.csv")
dicionario = pd.read_csv("dados/dicionario.csv")
empreendimento = pd.read_csv("dados/empreendimento_2025.csv")

In [29]:
print(f"A base principal operacao_2025.csv possui {operacao.shape[0]} registros e {operacao.shape[1]} colunas.")
print(f"A base segundaria empreendimento_2025.csv possui {empreendimento.shape[0]} registros e {empreendimento.shape[1]} colunas.")
print(f"A base dicionario.csv possui {dicionario.shape[0]} registros e {dicionario.shape[1]} colunas.")

A base principal operacao_2025.csv possui 2442343 registros e 15 colunas.
A base segundaria empreendimento_2025.csv possui 1050 registros e 10 colunas.
A base dicionario.csv possui 52 registros e 5 colunas.

In [35]:
print(f"O nomes das colunas da base principal operacao_2025.csv e {operacao.columns.tolist()}")
print(f"O nomes das colunas da segundaria empreendimento_2025.csv e {empreendimento.columns.tolist()}")
print(f"O nomes das colunas da base dicionario.csvcsv e {dicionario.columns.tolist()}")

O nomes das colunas da base principal operacao_2025.csv e ['ano_emissao', 'mes_emissao', 'data_emissao', 'data_vencimento', 'sigla_uf', 'id_referencia_bacen', 'numero_ordem', 'id_categoria_emitente', 'id_empreendimento', 'id_fonte_recurso', 'id_instrumento_credito', 'valor_parcela_credito', 'valor_quantidade_itens_financiados', 'valor_recurso_proprio', 'valor_receita_bruta_esperada']
O nomes das colunas da segundaria empreendimento_2025.csv e ['id_empreendimento', 'data_inicio', 'data_fim', 'finalidade', 'atividade', 'modalidade', 'produto', 'variedade', 'zoneamento', 'unidade_medida']
O nomes das colunas da base dicionario.csvcsv e ['id_tabela', 'nome_coluna', 'chave', 'cobertura_temporal', 'valor']

In [40]:
print("O nomes das colunas da base principal operacao_2025.csv e:")
for numero, coluna in enumerate(operacao.columns, start=1):    
    print(f"{numero}. {coluna}")

O nomes das colunas da base principal operacao_2025.csv e:
1. ano_emissao
2. mes_emissao
3. data_emissao
4. data_vencimento
5. sigla_uf
6. id_referencia_bacen
7. numero_ordem
8. id_categoria_emitente
9. id_empreendimento
10. id_fonte_recurso
11. id_instrumento_credito
12. valor_parcela_credito
13. valor_quantidade_itens_financiados
14. valor_recurso_proprio
15. valor_receita_bruta_esperada

In [42]:
operacao.head(15)

,ano_emissao,mes_emissao,data_emissao,data_vencimento,sigla_uf,id_referencia_bacen,numero_ordem,id_categoria_emitente,id_empreendimento,id_fonte_recurso,id_instrumento_credito,valor_parcela_credito,valor_quantidade_itens_financiados,valor_recurso_proprio,valor_receita_bruta_esperada
0,2025,11,2025-11-12,2026-11-11,AL,521092090,1,2222,12010040000041,201,1,30000.00,NaN,NaN,126500.00
1,2025,4,2025-04-08,2026-11-30,AL,519741649,1,2222,12010040000041,201,10,93225.68,NaN,0.00,408135.00
2,2025,3,2025-03-13,2026-11-30,AL,519609806,1,2222,12010040000041,300,10,86845.56,NaN,0.00,394530.50
3,2025,4,2025-04-08,2026-11-30,AL,519741594,1,2222,12010040000041,201,10,33960.78,NaN,0.00,145762.50
4,2025,2,2025-02-18,2026-12-10,AL,519516592,1,2222,12010040000041,201,10,31230.17,NaN,0.00,141401.00
5,2025,1,2025-01-22,2026-12-15,AL,519400863,1,2222,12010040000041,300,10,64385.50,NaN,0.00,292496.75
6,2025,4,2025-04-22,2026-12-23,AL,519802559,1,2222,12010040000041,201,10,54087.94,NaN,0.00,211575.00
7,2025,9,2025-09-11,2027-02-23,AL,520692366,1,2222,12010040000041,201,10,18797.62,NaN,0.00,66300.00
8,2025,9,2025-09-11,2027-03-05,AL,520693173,1,2222,12010040000041,201,1,190000.00,NaN,40000.00,280000.00
9,2025,12,2025-12-02,2027-07-15,AL,521222018,1,2222,12010040000041,201,10,188420.72,NaN,0.00,691600.00
10,2025,9,2025-09-22,2027-09-09,AL,520761669,1,2222,12010040000041,201,5,250000.00,NaN,90625.01,400000.00
11,2025,6,2025-06-04,2026-12-27,AL,520042771,2,2222,12010040000043,201,10,14955.18,NaN,0.00,39195.00
12,2025,5,2025-05-22,2027-05-22,AL,519964366,1,2222,12010040000043,502,5,43644.48,NaN,NaN,87288.96
13,2025,2,2025-02-17,2026-08-10,AM,519509986,1,2222,12010160000041,501,5,99655.27,NaN,0.00,179595.50
14,2025,1,2025-01-30,2027-01-10,AM,519441093,1,2222,12010160000041,501,5,18718.67,NaN,0.00,178480.00

In [ ]:
print("O nomes das colunas da base principal empreendimento_2025.csv e:")
for numero, coluna in enumerate(empreendimento.columns, start=1):    
    print(f"{numero}. {coluna}")

In [ ]:
empreendimento.head(20)

In [ ]:
dicionario.head(15)

In [49]:
dicionario_categoria = dicionario[dicionario["nome_coluna"] == "id_categoria_emitente"]
display(dicionario_categoria)

,id_tabela,nome_coluna,chave,cobertura_temporal,valor
0,operacao,id_categoria_emitente,2222,2013(1),Pequeno Produtor Rural
1,operacao,id_categoria_emitente,3333,2013(1),Médio Produtor Rural
2,operacao,id_categoria_emitente,4444,2013(1),Grande Produtor Rural
3,operacao,id_categoria_emitente,5555,2012(1)2013,Todas Categorias de Produtores Rurais
4,operacao,id_categoria_emitente,7777,2013(1)2018,Repasse a Cooperativa Singular de Crédito
5,operacao,id_categoria_emitente,8888,2013(1)2018,Repasse a Cooperativa Central de Crédito

In [ ]:
operacao = dicionario_categoria.merge(operacao, left_on= "id_categoria_emitente", right_on= "valor", how="left")