In [19]:
import pandas as pd
import numpy as np

operacao = pd.read_csv("dados/operacao_2025.csv")
dicionario = pd.read_csv("dados/dicionario.csv")
empreendimento = pd.read_csv("dados/empreendimento_2025.csv")

In [20]:
print(f"A base principal operacao_2025.csv possui {operacao.shape[0]} registros e {operacao.shape[1]} colunas.")
print(f"A base segundaria empreendimento_2025.csv possui {empreendimento.shape[0]} registros e {empreendimento.shape[1]} colunas.")
print(f"A base dicionario.csv possui {dicionario.shape[0]} registros e {dicionario.shape[1]} colunas.")

A base principal operacao_2025.csv possui 2442343 registros e 15 colunas.
A base segundaria empreendimento_2025.csv possui 1050 registros e 10 colunas.
A base dicionario.csv possui 52 registros e 5 colunas.

In [21]:
print(f"O nomes das colunas da base principal operacao_2025.csv e {operacao.columns.tolist()}")
print(f"O nomes das colunas da segundaria empreendimento_2025.csv e {empreendimento.columns.tolist()}")
print(f"O nomes das colunas da base dicionario.csvcsv e {dicionario.columns.tolist()}")

O nomes das colunas da base principal operacao_2025.csv e ['ano_emissao', 'mes_emissao', 'data_emissao', 'data_vencimento', 'sigla_uf', 'id_referencia_bacen', 'numero_ordem', 'id_categoria_emitente', 'id_empreendimento', 'id_fonte_recurso', 'id_instrumento_credito', 'valor_parcela_credito', 'valor_quantidade_itens_financiados', 'valor_recurso_proprio', 'valor_receita_bruta_esperada']
O nomes das colunas da segundaria empreendimento_2025.csv e ['id_empreendimento', 'data_inicio', 'data_fim', 'finalidade', 'atividade', 'modalidade', 'produto', 'variedade', 'zoneamento', 'unidade_medida']
O nomes das colunas da base dicionario.csvcsv e ['id_tabela', 'nome_coluna', 'chave', 'cobertura_temporal', 'valor']

In [22]:
print("O nomes das colunas da base principal operacao_2025.csv e:")
for numero, coluna in enumerate(operacao.columns, start=1):    
    print(f"{numero}. {coluna}")

O nomes das colunas da base principal operacao_2025.csv e:
1. ano_emissao
2. mes_emissao
3. data_emissao
4. data_vencimento
5. sigla_uf
6. id_referencia_bacen
7. numero_ordem
8. id_categoria_emitente
9. id_empreendimento
10. id_fonte_recurso
11. id_instrumento_credito
12. valor_parcela_credito
13. valor_quantidade_itens_financiados
14. valor_recurso_proprio
15. valor_receita_bruta_esperada

In [23]:
operacao.head(5)

,ano_emissao,mes_emissao,data_emissao,data_vencimento,sigla_uf,id_referencia_bacen,numero_ordem,id_categoria_emitente,id_empreendimento,id_fonte_recurso,id_instrumento_credito,valor_parcela_credito,valor_quantidade_itens_financiados,valor_recurso_proprio,valor_receita_bruta_esperada
0,2025,11,2025-11-12,2026-11-11,AL,521092090,1,2222,12010040000041,201,1,30000.00,NaN,NaN,126500.0
1,2025,4,2025-04-08,2026-11-30,AL,519741649,1,2222,12010040000041,201,10,93225.68,NaN,0.0,408135.0
2,2025,3,2025-03-13,2026-11-30,AL,519609806,1,2222,12010040000041,300,10,86845.56,NaN,0.0,394530.5
3,2025,4,2025-04-08,2026-11-30,AL,519741594,1,2222,12010040000041,201,10,33960.78,NaN,0.0,145762.5
4,2025,2,2025-02-18,2026-12-10,AL,519516592,1,2222,12010040000041,201,10,31230.17,NaN,0.0,141401.0

In [37]:
# Transformar coluna de datas que estavam em str para date 
operacao['data_vencimento'] = pd.to_datetime(operacao['data_vencimento'])
print(operacao['data_vencimento'].dtype) 
operacao['data_emissao'] = pd.to_datetime(operacao['data_emissao']) 
print(operacao['data_emissao'].dtype)

datetime64[us]
datetime64[us]

In [24]:
print("O nomes das colunas da base principal empreendimento_2025.csv e:")
for numero, coluna in enumerate(empreendimento.columns, start=1):    
    print(f"{numero}. {coluna}")

O nomes das colunas da base principal empreendimento_2025.csv e:
1. id_empreendimento
2. data_inicio
3. data_fim
4. finalidade
5. atividade
6. modalidade
7. produto
8. variedade
9. zoneamento
10. unidade_medida

In [25]:
empreendimento.head(5)

,id_empreendimento,data_inicio,data_fim,finalidade,atividade,modalidade,produto,variedade,zoneamento,unidade_medida
0,23271400000002,1984-01-01,NaN,Investimento,Pecuário(a),AQUISIÇÃO DE ANIMAIS,BÚFALOS (BUBALINOS),NÃO SE APLICA,Não zoneado,Unidade
1,23271300193002,1984-01-01,NaN,Investimento,Pecuário(a),AQUISIÇÃO DE ANIMAIS,BOVINOS,LEITE - MATRIZES (VACAS E CRIAS FÊMEAS PARA P...,Não zoneado,Unidade
2,23276760000002,1984-01-01,NaN,Investimento,Pecuário(a),AQUISIÇÃO DE ANIMAIS,SUÍNOS,NÃO SE APLICA,Não zoneado,Unidade
3,23275580000002,1984-01-01,NaN,Investimento,Pecuário(a),AQUISIÇÃO DE ANIMAIS,OVINOS,NÃO SE APLICA,Não zoneado,Unidade
4,23270820015002,1984-01-01,NaN,Investimento,Pecuário(a),AQUISIÇÃO DE ANIMAIS,APICULTURA,"ABRANGE COMPRA DE ABELHAS, ISOLADAMENTE OU EM ...",Não zoneado,Unidade

In [26]:
dicionario.head(15)

,id_tabela,nome_coluna,chave,cobertura_temporal,valor
0,operacao,id_categoria_emitente,2222,2013(1),Pequeno Produtor Rural
1,operacao,id_categoria_emitente,3333,2013(1),Médio Produtor Rural
2,operacao,id_categoria_emitente,4444,2013(1),Grande Produtor Rural
3,operacao,id_categoria_emitente,5555,2012(1)2013,Todas Categorias de Produtores Rurais
4,operacao,id_categoria_emitente,7777,2013(1)2018,Repasse a Cooperativa Singular de Crédito
5,operacao,id_categoria_emitente,8888,2013(1)2018,Repasse a Cooperativa Central de Crédito
6,operacao,id_fonte_recurso,100,2011(1)2099,TESOURO NACIONAL
7,operacao,id_fonte_recurso,201,2011(1)2099,OBRIGATÓRIOS - MCR 6.2
8,operacao,id_fonte_recurso,202,2019(1)2019,EXIGIBILIDADE ADICIONAL DOS RECURSOS À VISTA
9,operacao,id_fonte_recurso,222,2022(1)2023,Exigibilidade Adicional dos Recursos à Vista -...
10,operacao,id_fonte_recurso,225,2023(1)2024,Exigibilidade Adicional dos Recursos à Vista -...
11,operacao,id_fonte_recurso,226,2024(1)2025,Exigibilidade Adicional dos Recursos à Vista -...
12,operacao,id_fonte_recurso,250,2012(1)2012,FACULDADE DE APLICAÇÃO - COMPULSÓRIO
13,operacao,id_fonte_recurso,260,2013(1)2015,COMPULSÓRIO SOBRE RECURSOS À VISTA - REFORÇO D...
14,operacao,id_fonte_recurso,300,2011(1)2099,POUPANÇA RURAL - CONTROLADOS - SUBVENÇÃO ECONÔ...

In [27]:
dicionario_categoria = dicionario[dicionario["nome_coluna"] == "id_categoria_emitente"]
display(dicionario_categoria)

,id_tabela,nome_coluna,chave,cobertura_temporal,valor
0,operacao,id_categoria_emitente,2222,2013(1),Pequeno Produtor Rural
1,operacao,id_categoria_emitente,3333,2013(1),Médio Produtor Rural
2,operacao,id_categoria_emitente,4444,2013(1),Grande Produtor Rural
3,operacao,id_categoria_emitente,5555,2012(1)2013,Todas Categorias de Produtores Rurais
4,operacao,id_categoria_emitente,7777,2013(1)2018,Repasse a Cooperativa Singular de Crédito
5,operacao,id_categoria_emitente,8888,2013(1)2018,Repasse a Cooperativa Central de Crédito

In [28]:
# União da tabela operacao com empreendimento através do id_empreendimento
df_resultado = pd.merge(
    operacao, 
    empreendimento, 
    on='id_empreendimento', 
    how='left'
)

# Filtro do dicionário com o id_fonte_recurso
dic_fonte = dicionario[dicionario['nome_coluna'] == 'id_fonte_recurso']
df_resultado = pd.merge(
    df_resultado,
    dic_fonte[['chave', 'valor']], 
    left_on='id_fonte_recurso',
    right_on='chave',
    how='left'
)

# Remove colunas com nomes identicos
df_resultado = df_resultado.loc[:, ~df_resultado.columns.duplicated()]

# Renomeia a coluna valor_y para o nome fonte_recurso_descricao
df_resultado = df_resultado.rename(columns={'valor_y': 'fonte_recurso_descricao'})

# 2. Exclui a coluna chave_y que ficou igual a id_fonte_recurso
df_resultado = df_resultado.drop(columns=['chave_y'], errors='ignore')

display(df_resultado.head(5))

,ano_emissao,mes_emissao,data_emissao,data_vencimento,sigla_uf,id_referencia_bacen,numero_ordem,id_categoria_emitente,id_empreendimento,id_fonte_recurso,...,data_fim,finalidade,atividade,modalidade,produto,variedade,zoneamento,unidade_medida,chave,valor
0,2025,11,2025-11-12,2026-11-11,AL,521092090,1,2222,12010040000041,201,...,NaN,Custeio,Agrícola,LAVOURA,ABACAXI,NÃO SE APLICA,Zoneado,Hectare,201,OBRIGATÓRIOS - MCR 6.2
1,2025,4,2025-04-08,2026-11-30,AL,519741649,1,2222,12010040000041,201,...,NaN,Custeio,Agrícola,LAVOURA,ABACAXI,NÃO SE APLICA,Zoneado,Hectare,201,OBRIGATÓRIOS - MCR 6.2
2,2025,3,2025-03-13,2026-11-30,AL,519609806,1,2222,12010040000041,300,...,NaN,Custeio,Agrícola,LAVOURA,ABACAXI,NÃO SE APLICA,Zoneado,Hectare,300,POUPANÇA RURAL - CONTROLADOS - SUBVENÇÃO ECONÔ...
3,2025,4,2025-04-08,2026-11-30,AL,519741594,1,2222,12010040000041,201,...,NaN,Custeio,Agrícola,LAVOURA,ABACAXI,NÃO SE APLICA,Zoneado,Hectare,201,OBRIGATÓRIOS - MCR 6.2
4,2025,2,2025-02-18,2026-12-10,AL,519516592,1,2222,12010040000041,201,...,NaN,Custeio,Agrícola,LAVOURA,ABACAXI,NÃO SE APLICA,Zoneado,Hectare,201,OBRIGATÓRIOS - MCR 6.2

In [29]:
print(dic_fonte)

   id_tabela       nome_coluna  chave cobertura_temporal  \
6   operacao  id_fonte_recurso    100        2011(1)2099
7   operacao  id_fonte_recurso    201        2011(1)2099
8   operacao  id_fonte_recurso    202        2019(1)2019
9   operacao  id_fonte_recurso    222        2022(1)2023
10  operacao  id_fonte_recurso    225        2023(1)2024
11  operacao  id_fonte_recurso    226        2024(1)2025
12  operacao  id_fonte_recurso    250        2012(1)2012
13  operacao  id_fonte_recurso    260        2013(1)2015
14  operacao  id_fonte_recurso    300        2011(1)2099
15  operacao  id_fonte_recurso    301        2011(1)2017
16  operacao  id_fonte_recurso    302        2011(1)2017
17  operacao  id_fonte_recurso    303        2011(1)2099
18  operacao  id_fonte_recurso    304        2019(1)2019
19  operacao  id_fonte_recurso    402        2011(1)2099
20  operacao  id_fonte_recurso    403        2011(1)2099
21  operacao  id_fonte_recurso    405        2011(1)2013
22  operacao  id_fonte_recurso    430        2013(1)2099
23  operacao  id_fonte_recurso    431        2023(1)2099
24  operacao  id_fonte_recurso    440        2016(1)2019
25  operacao  id_fonte_recurso    450        2012(1)2021
26  operacao  id_fonte_recurso    451        2021(1)2099
27  operacao  id_fonte_recurso    501        2011(1)2099
28  operacao  id_fonte_recurso    502        2011(1)2099
29  operacao  id_fonte_recurso    503        2011(1)2099
30  operacao  id_fonte_recurso    505        2011(1)2099
31  operacao  id_fonte_recurso    506        2013(1)2099
32  operacao  id_fonte_recurso    507        2011(1)2099
33  operacao  id_fonte_recurso    520        2011(1)2099
34  operacao  id_fonte_recurso    600        2011(1)2099
35  operacao  id_fonte_recurso    650        2011(1)2099
36  operacao  id_fonte_recurso    680        2011(1)2013
37  operacao  id_fonte_recurso    800        2011(1)2099
38  operacao  id_fonte_recurso    850        2011(1)2099
39  operacao  id_fonte_recurso    900        2011(1)2099
40  operacao  id_fonte_recurso    990        2011(1)2015

                                                valor
6                                    TESOURO NACIONAL
7                              OBRIGATÓRIOS - MCR 6.2
8        EXIGIBILIDADE ADICIONAL DOS RECURSOS À VISTA
9   Exigibilidade Adicional dos Recursos à Vista -...
10  Exigibilidade Adicional dos Recursos à Vista -...
11  Exigibilidade Adicional dos Recursos à Vista -...
12               FACULDADE DE APLICAÇÃO - COMPULSÓRIO
13  COMPULSÓRIO SOBRE RECURSOS À VISTA - REFORÇO D...
14  POUPANÇA RURAL - CONTROLADOS - SUBVENÇÃO ECONÔ...
15   POUPANÇA RURAL - CONTROLADOS - CONDIÇÕES MCR 6.2
16  POUPANÇA RURAL - CONTROLADOS - FATOR DE PONDER...
17                             POUPANÇA RURAL - LIVRE
18          EXIGIBILIDADE ADICIONAL DA POUPANÇA RURAL
19                                    RECURSOS LIVRES
20                       RECURSOS LIVRES EQUALIZÁVEIS
21                               FUNDO DE COMMODITIES
22  LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - TAXA L...
23  LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - CONTRO...
24  LETRA DE CRÉDITO DO AGRONEGÓCIO (LCA) - TAXA F...
25  INSTR HIBRIDO CAPITAL DÍVIDA-IHCD (Lei 12.793/...
26  INSTR HIBRIDO CAPITAL DÍVIDA-IHCD (Lei 12.793/...
27  FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO NORTE...
28  FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO NORDE...
29  FUNDO CONSTITUCIONAL DE FINANCIAMENTO DO CENTR...
30                         BNDES/FINAME - EQUALIZÁVEL
31                                        BNDES LIVRE
32                                              INCRA
33               FUNDO DE TERRAS E DA REFORMA AGRÁRIA
34          GOVERNOS E FUNDOS ESTADUAIS OU MUNICIPAIS
35               FAT - FUNDO DE AMPARO AO TRABALHADOR
36                                          PIS/PASEP
37       FUNCAFE-FUNDO DE DEFESA DA ECONOMIA CAFEEIRA
38                                   CAPTAÇÃO EXTERNA
39  ATIVIDADE NÃO FINANCIADA ENQUADRADA NO PROAGRO...
40        OUTRAS FONTES DE RECURSOS NÃO ESPECIFICADAS

In [30]:
print(f"A base df_resultado possui {df_resultado.shape[0]} registros e {df_resultado.shape[1]} colunas.")

A base df_resultado possui 2442343 registros e 26 colunas.

In [31]:
contagem_uf = df_resultado['sigla_uf'].value_counts()

print(contagem_uf)
print(contagem_uf.sum())
print()

sigla_uf
BA    327682
MG    272657
RS    256161
CE    190471
PI    174798
PR    164549
MA    147594
PE    146936
SC    132381
PB    108674
RN     76872
AL     57800
GO     51481
PA     51242
SE     48245
SP     46422
ES     46250
MT     35775
RO     31028
MS     30644
TO     16240
AC     10175
AM      6301
RJ      5263
AP      3337
RR      2898
DF       467
Name: count, dtype: int64
2442343

In [32]:
#produto mais frequente por UF
produto_por_uf = df_resultado.groupby('sigla_uf')['produto'].apply(
    lambda x: x.value_counts().index[0] if not x.dropna().empty else None
).reset_index()

produto_por_uf.columns = ['sigla_uf', 'produto_mais_frequente']

print(produto_por_uf)

   sigla_uf                             produto_mais_frequente
0        AC                                            BOVINOS
1        AL                                            BOVINOS
2        AM                                            PESCADO
3        AP                                            PESCADO
4        BA                                            BOVINOS
5        CE                                            BOVINOS
6        DF                                               SOJA
7        ES                                               CAFÉ
8        GO                                            BOVINOS
9        MA  Terraços, Porteiras, Mata-burros, Currais, Coc...
10       MG                                            BOVINOS
11       MS                                            BOVINOS
12       MT                                            BOVINOS
13       PA                                            BOVINOS
14       PB                                            BOVINOS
15       PE                                            BOVINOS
16       PI  Terraços, Porteiras, Mata-burros, Currais, Coc...
17       PR                                               SOJA
18       RJ                                            BOVINOS
19       RN                                            BOVINOS
20       RO                                            BOVINOS
21       RR                                            BOVINOS
22       RS                                            BOVINOS
23       SC                                            BOVINOS
24       SE                                            BOVINOS
25       SP                                            BOVINOS
26       TO                                            BOVINOS

In [33]:
#Conta quantos contratos tem por tipo de produto
contagem_produto = df_resultado['produto'].value_counts()
with pd.option_context('display.max_rows', None):
    print(contagem_produto)

produto
BOVINOS                                                                                                 664395
Terraços, Porteiras, Mata-burros, Currais, Cochos, Cercas                                               222774
SOJA                                                                                                    138322
Aquisição de caixas d'água, lonas, toldos, campânulas                                                   119020
MILHO                                                                                                   103219
Residências Rurais                                                                                       97908
CAFÉ                                                                                                     80118
Construção/Recuperação Barragem/Tanque, sistemas captação de água                                        63555
PASTAGEM                                                                                                 60591
MÁQUINAS E IMPLEMENTOS                                                                                   58677
OVINOS                                                                                                   47971
IRRIGAÇÃO/LIXIVIAÇÃO (GOTEJADOR, ASPERSOR, NEBULIZADOR, EXAUSTOR, VENTILADOR, MANGUEIRAS, CANAIS ET)     40827
Implantação de tecnologias de energia renovável, ambiental e pequenas aplicações hidroenergéticas        40718
Instalações para Aves, Suínos e Coelhos                                                                  35514
TRATOR                                                                                                   31914
IRRIGAÇÃO                                                                                                30985
ARMAZÉM, DEPÓSITO, SILO, GALPÃO, PAIOL, ESTUFA E INSTALAÇÕES CONGÊNERES                                  29177
TRIGO                                                                                                    28332
PESCADO                                                                                                  27036
SUÍNOS                                                                                                   26140
MÁQUINAS, APARELHOS E INSTRUMENTOS PARA PROCESSAMENTO E BENEFICIAMENTO  DE  PRODUTOS                     24040
AQUISIÇÃO DE FERRAMENTAS E TUBOS                                                                         20738
AQUISIÇÃO DE UTENSÍLIOS DOMÉSTICOS PARA USO EM MEIO RURAL                                                18322
AQUISIÇÃO DE EQUIPAMENTOS DE INFORMÁTICA E TELECOMUNICAÇÕES, INCLUINDO AQUISIÇÃO DE SOFTWARE             17773
CAPRINOS                                                                                                 17335
CORREÇÃO INTENSIVA DO SOLO                                                                               16842
Perfuração Poço, Cacimba/Cisterna                                                                        15643
MANDIOCA (AIPIM, MACAXEIRA)                                                                              14246
CANA-DE-AÇUCAR                                                                                           14115
Embarcação Pequena (até 20 A/B)                                                                          13797
CARRETAS, CARROÇAS E VAGÕES DE CARGA, FORRAGEIROS E DEMAIS                                               12988
BANANA                                                                                                   11847
MARACUJÁ                                                                                                  9974
COLHEITADEIRAS, COLHEDEIRAS E ARRANCADEIRAS                                                               9833
AGROARTESANATO                                                                                            9698
ARROZ                                                                                                     9044
CACAU                                                                                                     8927
ABERTURA DE GLEBAS RURAIS                                                                                 8892
AVICULTURA                                                                                                8747
LAGO ARTIFICIAL, TANQUE, BARREIROS, CANAIS, RESERV.ÁGUA POTAVEL                                           8551
APICULTURA                                                                                                8066
AÇAÍ                                                                                                      7693
AQUISIÇÃO DE MOTORES E ELEVADORES                                                                         7535
AQUISIÇÃO DE MAQUINA(S)/EQUIPAMENTO(S) PARA EXTRAÇÃO/FABRICAÇÃO (INCLUINDO GUINCHOS E GUINDASTES)         7518
INSTALAÇÃO/MONTAGEM/TRANSPORTE DE EQUIPAMENTO(S)                                                          7269
ESTUFAS/VIVEIROS (ILUMIN. ARTIFICIAL, MUDAS, SEMENTES, SACOS, TALAGARÇAS, BANDEJAS, VASOS)                6940
UVA                                                                                                       6745
CEBOLA                                                                                                    6023
LARANJA                                                                                                   5840
Unidade de Beneficiamento ou Processamento                                                                5135
GRANJAS AVÍCOLAS                                                                                          5114
Caixas de abelhas, favos, centrifugas p/ extração de mel, fumegadores                                     5107
ADUBAÇÃO ORGÂNICA/MINERAL, CALAGEM, SUBSTRATOS INERTES(PEDRA, AREIA, VERMICULITA, SILTE, ARGILA ETC)      4520
TOMATE                                                                                                    4364
FEIJÃO                                                                                                    4302
PEIXE                                                                                                     4222
Aquisição de Sistemas para Rastreabilidade de bovinos e bubalinos                                         4121
ESCOLAS RURAIS                                                                                            4107
AGROINDÚSTRIA                                                                                             4001
MÁQUINAS, APARELHOS E INSTRUMENTOS                                                                        3983
GALINÁCEOS                                                                                                3906
FUMO                                                                                                      3745
REBOQUES, SEMIREBOQUES, CAÇAMBAS E CABINES                                                                3670
CAMIONETAS                                                                                                3239
AQUISIÇÃO DE AQUECEDORES, GERADORES, INCINERADORES, COMPRESSORES, VENTILADORES E APAR. DE AR CONDIC.      3065
AVES                                                                                                      2885
ADUBAÇÃO INTENSIVA DO SOLO                                                                                2876
MORANGO                                                                                                   2642
MAÇÃ                                                                                                      2493
INSTALAÇÕES PARA INDUSTRIALIZAÇÃO E BENEFICIAMENTO                                                        2421
VACINAS, SAIS MINERAIS E MEDICAMENTOS                                                                     2392
AVEIA                                                                                                     2337
AQUISIÇÃO DE FERRAMENTA PORTÁTIL MANUAL PARA TRATOS CULTURAIS                                             2119
REFORMAS  DE  MÁQUINAS, APARELHOS, EQUIPAMENTOS  E VEÍCULOS, COMPRA DE PECAS E ACESSRIOS                  2006
CAMINHÕES                                                                                                 1901
FUNDIÁRIOS                                                                                                1869
ERVA-MATE                                                                                                 1793
AQUISIÇÃO DE DESTILADORES, FILTROS, DEPURADORES E DOSADORES                                               1703
ABACAXI                                                                                                   1669
CAJU                                                                                                      1603
PALMA                                                                                                     1551
PIMENTA-DO-REINO                                                                                          1541
PÊSSEGO                                                                                                   1534
PROTEÇÃO DO SOLO                                                                                          1437
PRODUTOS AQUICOLAS (Armazenamento, Acondicionamento e Preservação, inclusive Seguro, Impostos etc)        1435
SISTEMAS DE CAPTAÇÃO, RETENÇÃO E APROVEITAMENTO DE ÁGUA                                                   1432
LIMÃO                                                                                                     1392
SECADOR                                                                                                   1357
MOTOCICLETAS E MOTONETAS                                                                                  1345
SORGO                                                                                                     1292
MANGA                                                                                                     1190
ABELHA                                                                                                    1121
EQUIPAMENTOS E UTENSILIOS PARA AGRICULTURA DE PRECISÃO                                                    1101
ALHO                                                                                                      1066
BATATA-INGLESA                                                                                            1056
TANGERINA                                                                                                 1043
Tanques Escavados                                                                                         1027
AMEIXA                                                                                                     986
MAMÃO                                                                                                      972
AMENDOIM                                                                                                   943
GOIABA                                                                                                     931
CANOLA                                                                                                     929
EUCALIPTO                                                                                                  921
TERREIROS                                                                                                  911
PIMENTÃO                                                                                                   896
VEÍCULO AÉREO NÃO TRIPULADO (DRONE)                                                                        861
AQUISIÇÃO DE INSUMOS PARA FORNECIMENTO AOS COOPERADOS                                                      849
ALFACE                                                                                                     842
GRANJAS DE SUÍNOS                                                                                          808
BETERRABA                                                                                                  781
EQUIPAMENTOS E UTENSÍLIOS PARA EXTRATIVISMO DE ESPÉCIES NATIVAS                                            716
ELETRIFICAÇÃO RURAL                                                                                        691
BRÓCOLOS (BRÓCOLIS)                                                                                        669
CEVADA                                                                                                     643
Confinamento de bovinos free stall""                                                                       626
ALGODÃO                                                                                                    595
JIPES, FURGÕES E SEMELHANTES                                                                               585
CENOURA                                                                                                    577
TENDA, GALPÃO, TÚNEL PLÁSTICO (ABRANGE LONAS, FILMES, LONGARINAS, ESTACAS E MAT. SUSTENTAÇÃO)              571
MATERIAIS INDUSTRIALIZADOS                                                                                 569
MELANCIA                                                                                                   534
Aerador                                                                                                    518
CERCAS, ARAMADOS, TELHAS, TELAS PARA SOMBREAMENTO E COBERTURAS DE SOLO                                     494
BÚFALOS (BUBALINOS)                                                                                        481
CHUCHU                                                                                                     481
ABÓBORA-MORANGA                                                                                            463
TURISMO E LAZER RURAL                                                                                      463
Hortaliça ora-pro-nóbis                                                                                    447
CAQUI                                                                                                      445
CAPIM                                                                                                      442
MANDIOQUINHA (BATATA: BAROA, SALSA, AIPO)                                                                  422
PLANTAS ORNAMENTAIS                                                                                        417
ABACATE                                                                                                    400
REPOLHO                                                                                                    385
BIODIGESTOR, ESTERQUEIRA, TANQUES DE OXIDAÇÃO BIOLÓGICA E TRATAMENTO DE ÁGUA E ESGOTO                      385
LEITE                                                                                                      381
PEPINO                                                                                                     370
SERINGUEIRA                                                                                                368
COCO-DA-BAIA                                                                                               359
DESPOLPADOR                                                                                                355
ACEROLA                                                                                                    345
DENDÊ                                                                                                      321
FLORESTAMENTO E REFLORESTAMENTO                                                                            313
GENGIBRE                                                                                                   303
COUVE-FLOR                                                                                                 301
FLORES                                                                                                     292
MAMONA                                                                                                     291
URUCUM                                                                                                     286
TULHA                                                                                                      285
INHAME                                                                                                     270
QUINTAIS PRODUTIVOS PARA MULHERES RURAIS                                                                   270
Embarcação Média (acima de 20 e abaixo de 100 A/B)                                                         253
TRICICLOS E QUADRICLOS                                                                                     253
CULTIVADOR                                                                                                 246
Matrizes e Reprodutores                                                                                    242
BATATA-DOCE                                                                                                238
HORTALIÇAS                                                                                                 234
AQUISIÇÃO DE EQUIPAMENTOS PARA MOLDAGEM, TORNOS, MOINHOS E PRENSA                                          217
CONSERVAÇÃO DE SOLOS                                                                                       217
Tanques Redes                                                                                              210
CARNAÚBA                                                                                                   207
FLORESTAMENTO - TRATOS CULTURAIS                                                                           203
GRAMA                                                                                                      202
PINUS                                                                                                      200
AGAVE (SISAL)                                                                                              184
Balança para Animais                                                                                       178
COCO                                                                                                       177
LAVADOR                                                                                                    174
BATATA                                                                                                     173
AVES EXCETO GALINÁCEOS                                                                                     173
CARCINICULTURA (Cultivo de Camarão e Lagosta)                                                              172
PITAYA                                                                                                     171
AQUISIÇÃO DE MATERIAL DE ESTOCAGEM/TRANSPORTE/SACARIA/CAIXAS                                               155
CARÁ                                                                                                       144
AQUISIÇÃO DE EQUIPAMENTOS PARA MANUTENÇÃO DE VEÍCULOS                                                      141
CAPITAL DE GIRO                                                                                            141
GRAVIOLA                                                                                                   135
CÂMARA FRIA PARA ARMAZENAMENTO DE FRUTAS                                                                   133
AÇUCAR                                                                                                     125
AQUISIÇÃO DE EMPILHADEIRA(S)/TOMBADORA(S)                                                                  125